config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index', as: 'home' #default page for localhost:3000
  					 #this is also the same page for localhost:3000/posts

  resources :posts do
    resources :comments
  end
=begin
           Prefix Verb   URI Pattern                                 Controller#Action
             home GET    /                                           posts#index
    post_comments GET    /posts/:post_id/comments(.:format)          comments#index
                  POST   /posts/:post_id/comments(.:format)          comments#create
 new_post_comment GET    /posts/:post_id/comments/new(.:format)      comments#new
edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format) comments#edit
     post_comment GET    /posts/:post_id/comments/:id(.:format)      comments#show
                  PATCH  /posts/:post_id/comments/:id(.:format)      comments#update
                  PUT    /posts/:post_id/comments/:id(.:format)      comments#update
                  DELETE /posts/:post_id/comments/:id(.:format)      comments#destroy
            posts GET    /posts(.:format)                            posts#index
                  POST   /posts(.:format)                            posts#create
         new_post GET    /posts/new(.:format)                        posts#new
        edit_post GET    /posts/:id/edit(.:format)                   posts#edit
             post GET    /posts/:id(.:format)                        posts#show
                  PATCH  /posts/:id(.:format)                        posts#update
                  PUT    /posts/:id(.:format)                        posts#update
                  DELETE /posts/:id(.:format)                        posts#destroy
            about GET    /about(.:format)                            pages#about
=end

  get 'about' => 'pages#about', as: 'about' #localhost:3000/about
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	#rake db:migrate to create the migration table
	has_many :comments
	validates :title, presence: true,
						length: {minimum: 1}
	validates :body, presence: true,
						length: {minimum: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	http_basic_authenticate_with name: "Alex", password: "1234", only: [:destroy]

	before_action :get, only: [:create, :destroy]

	def get
		@post = Post.find(params[:post_id]) #get/show the single post
	end


	def index

	end


	def show

	end


	def new

	end


	def create
		@comment = @post.comments.create(comment_params)
		redirect_to post_path(@post)
	end


	def edit

	end


	def update

	end


	def destroy
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end


	private def comment_params
		params.require(:comment).permit(:username, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = 'About Us';
		@content = 'This is the about page and this is the paragraph that explains the use/function of this page. I would like to make this long so that I can see some actual wrapping on the web side.';
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	#Make a funcName.html.erb view for nearly all methods specified in a controller
	#Use singular names for Models and plural names for Controllers

	http_basic_authenticate_with name: "Alex", password: "1234", except: [:index, :show]

	before_action :get, only: [:show, :edit, :update, :destroy]

	def get
		@post = Post.find(params[:id]) #get/show the single post
	end


	def index
		@posts = Post.all
	end


	def show
		
	end


	def new
		@post = Post.new
	end


	def create
		#render plain: params[:post].inspect
		@post = Post.new(post_params) #new post with title and body
		if (@post.save) #save the new post
			redirect_to @post #redirect the page to the new post created
		else
			render 'new'
		end
	end


	def edit
		
	end


	def update
		if (@post.update(post_params)) #save the new post
			redirect_to @post #redirect the page to the new post created
		else
			render 'edit'
		end
	end


	def destroy
		@post.destroy
		redirect_to posts_path
	end


	private def post_params #not accessible by user
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h4>Comments</h4>
<% @post.comments.each do |comment|%>
	<div class = 'well'>
		<p> <strong> <%= comment.username %> </strong>: <%= comment.body %> 
			<%= link_to "[X]", [comment.post, comment], 
							method: :delete,
							data: {confirm: 'Are you sure?'} %>
		</p>
	</div>
<% end %>

app/views/comments/_form.html.erb
<h4>Add Comment</h4>
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :username %> <br>
		<%= f.text_field(:username, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :body %> <br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!---->
<!--
  -->
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="#">SimpleBlog</a>
      <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>-->

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li> <%= link_to "Home", home_path %> </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li> <%= link_to "Create Post", new_post_path %> </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1> <%= @title %> </h1>
<p> <%= @content %> </p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class = "alert alert-danger"> <%= msg %> </div>
		<% end %>
	<% end %>

	<p>
		<%= f.label :title %> <br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :body %> <br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end -%>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %> <!--only use '%=' for output lines-->
	<div class = "well">
		<h3> <%= post.title %> </h3>
		<p> <%= post.body %> </p>
		<%= link_to "Read More", post_path(post), :class => 'btn btn-primary' %>
	</div>
<% end %>

app/views/posts/new.html.erb
<h1>Add New Post</h1>
<%= form_for :post, url: posts_path do |f| %>

	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class = "alert alert-danger"> <%= msg %> </div>
		<% end %>
	<% end %>

	<p>
		<%= f.label :title %> <br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :body %> <br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/posts/show.html.erb
<h2> <%= @post.title %> </h2>
<p> <%= @post.body %> </p>
<hr>
	<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-primary' %>
	<%= link_to "Delete", post_path(@post), 
							method: :delete,
							data: {confirm: 'Are you sure?'},
							:class => 'btn btn-danger' %>


<%= render 'comments/comments' %>
<%= render 'comments/form' %>